# Generated by Django 6.0.4 on 2026-05-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPServerModel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=389)),
                ('protocol', models.CharField(default='ldap', max_length=5)),
                ('base_dn', models.CharField(max_length=512)),
                ('bind_dn', models.CharField(max_length=512)),
                ('bind_password', models.CharField(max_length=512)),
                ('timeout', models.IntegerField(default=10)),
                ('use_tls', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ldap_servers',
            },
        ),
    ]
