# Generated by Django 6.0.4 on 2026-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_smtpconfig_systemrole_ldapservermodel_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapservermodel',
            name='attribute_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
