# Generated by Django 6.0.4 on 2026-05-22 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_ldapservermodel_attribute_mappings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('dominios', models.JSONField(default=list)),
                ('ou', models.CharField(blank=True, default='', max_length=512)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADA', 'Ejecutada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('ejecutado_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes',
                'ordering': ['-created_at'],
            },
        ),
    ]
