# Generated by Django 6.0.4 on 2026-05-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_solicitudes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('db', 'Solo base de datos'), ('ldap', 'Solo LDAP'), ('both', 'Base de datos + LDAP')], default='db', max_length=10)),
                ('ldap_bind_template', models.CharField(blank=True, default='', help_text='Ej: {username}@domain.com o CN={username},OU=Users,DC=...', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ldap_server', models.ForeignKey(blank=True, help_text='Servidor LDAP para autenticación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persistence.ldapservermodel')),
            ],
            options={
                'db_table': 'auth_config',
            },
        ),
    ]
