# Generated by Django 6.0.4 on 2026-05-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_auth_config_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dn', models.CharField(help_text='DN completo del grupo LDAP/AD (ej: CN=Admin,OU=Groups,DC=...)', max_length=512)),
                ('priority', models.IntegerField(default=0, help_text='Menor número = mayor prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ldap_server', models.ForeignKey(help_text='Servidor LDAP donde existe el grupo', on_delete=django.db.models.deletion.CASCADE, to='persistence.ldapservermodel')),
                ('role', models.ForeignKey(help_text='Rol del sistema a asignar', on_delete=django.db.models.deletion.CASCADE, to='persistence.systemrole')),
            ],
            options={
                'db_table': 'ldap_role_mappings',
                'ordering': ['priority'],
                'unique_together': {('ldap_server', 'group_dn')},
            },
        ),
    ]
