# Generated by Django 6.0.5 on 2026-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_ldaprolemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
